name = "stripe-webhook"
main = "index.js"
compatibility_date = "2024-01-01"

[vars]
PROCESSING_API_KEY = "mmw-proc-2024-secure-key"

[env.production]
name = "stripe-webhook"

[env.development]
name = "stripe-webhook-dev"